stages:
  preprocess:
    cmd: C:/Users/User/Downloads/ML-System-Design-with-DVC/.venv/Scripts/python.exe -m src.preprocess
    deps:
      - data/raw/stroke_risk_prediction_dataset.csv
      - src/preprocess.py
    params:
      - preprocess.raw_data_path
      - preprocess.train_data_path
      - preprocess.test_data_path
      - preprocess.target_column
      - preprocess.test_size
      - preprocess.random_state
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: C:/Users/User/Downloads/ML-System-Design-with-DVC/.venv/Scripts/python.exe -m src.train
    deps:
      - data/processed/train.csv
      - src/train.py
    params:
      - train.train_data_path
      - train.model_path
      - train.n_estimators
      - train.max_depth
      - train.learning_rate
      - train.random_state
    outs:
      - models/model.joblib

  evaluate:
    cmd: C:/Users/User/Downloads/ML-System-Design-with-DVC/.venv/Scripts/python.exe -m src.evaluate
    deps:
      - data/processed/test.csv
      - models/model.joblib
      - src/evaluate.py
    metrics:
      - metrics.json:
          cache: false